# A working compose for a simple dev environment using node, mongo and express.

services:
  crud-container:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:ro
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      # ********Research the line below, does not seem to be neccessary if both containers running in the same network.
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
