# A working compose for a simple dev environment using node, mongo and express.

services:
  crud-container:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:ro #bindmount mounts all the appropriate files to the app dir in the container and makes it read only (:ro)
      #- /app/node_modules #persists the data in node modules.
    environment:
      - PORT=3000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /data:/data/db #persits the db changes
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      # trasnlates below**** mongodb://${INITDB_ROOT_USERNAME}:${INITBD_ROOT_PASSWORD@service:ports}
      #service (mongo) is resolved by docker to be the port at which the mongo servie is running
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
